### ISSUE TITLE
❓ API docs?

### ISSUE THREAD

**Issue by joebernard** [margelo/react-native-vision-camera#10]
I was hoping to explore some API docs for the camera. Do you have those available somewhere or should I just rely on the example app for now?

**Comment by mrousavy** [comment]
Hi! I currently don't have docs for web-viewing available, but everything is thoroughly documented in the JSDoc (TypeScript definitions). Ideally I want to automatically build those and host them on GitHub pages, will have to take a look at that when I find some free time. 👍

**Comment by mrousavy** [comment]
Let's leave this issue open until docs are available

**Comment by mrousavy** [comment]
Hey! Forgot to get back to you. Docs are live at [cuvent.github.io/react-native-vision-camera](https://cuvent.github.io/react-native-vision-camera/), and API is automatically generated at [/docs/api](https://cuvent.github.io/react-native-vision-camera/docs/api) - let me know what you think 😄👍

**Comment by joebernard** [comment]
Excellent. I'm using `react-native-camera` right now and was always disappointed I could not use the multiple lenses on the later iPhones.  Really excited to experiment with this and having good docs will help.
