### ISSUE TITLE
🐛  The 'kotlin-android-extensions' Gradle plugin is deprecated. 

### ISSUE THREAD

**Issue by grkemtneri** [margelo/react-native-vision-camera#105]

**Comment by mrousavy** [comment]
That's a warning, not an error. You must be getting another error somewhere, could you share the full logs?

**Comment by grkemtneri** [comment]
sorry I missed it. I got a Java heap space error. I solved the problem and have successfully built now. thank you for your quick reply.

**Comment by Bamorem** [comment]
Hi, I have the same bug, but on my side it's not just a warning (The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-vision-camera'), see the log:

> Configure project :react-native-vision-camera
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-pager-view', ':react-native-vision-camera'

> Task :app:checkDebugAarMetadata FAILED
 
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: androidx.camera:camera-view:1.0.0-alpha29.
     AAR metadata file: /Users/yohanbalassiano/.gradle/caches/transforms-3/efbc1f4ee18ee6b315a8fb89da178f3c/transformed/jetified-camera-view-1.0.0-alpha29/META-INF/com/android/build/gradle/aar-metadata.properties.


When i remove react-native-vision-camera and react-native-reanimated it works again...

**Comment by mrousavy** [comment]
This is still a warning, read the actual error message.

> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.camera:camera-view:1.0.0-alpha29.

**Comment by nimblemo** [comment]
Have same error

**Comment by lrxiang222** [comment]
Have same error

**Comment by lrxiang222** [comment]
> This is still a warning, read the actual error message.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
> > The minCompileSdk (31) specified in a
> > dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
> > is greater than this module's compileSdkVersion (android-30).
> > Dependency: androidx.camera:camera-view:1.0.0-alpha29.

I was able to get my build working by adding this to my build.gradle file:

classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.71'
