### ISSUE TITLE
🐛 after the installation Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by qesya** [margelo/react-native-vision-camera#121]
Execution failed for task ':app:processDebugResources'. > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade    > Android resource linking failed

## Type

* [x] I'm cannot build my project with VisionCamera
* [ ] I'm experiencing a full app crash
* [ ] A feature is not working correctly
* [ ] Other: __________________

## Reproducable sample

```tsx
// code here
```

## Environment

* Platform(s):
  * [ ] iOS
  * [x] Android
* react-native version: ___
* react-native-vision-camera version: ___
* react-native-reanimated version: N/A

**Comment by mrousavy** [comment]
1. Please share your entire logs. The line that says "A failure occured" does not contain any relevant information.
2. Can you run the example app?

**Comment by mrousavy** [comment]
closing as it seems stale. let me know if you're still having issues & i'll reopen
