### ISSUE TITLE
🐛 Example app error on Android

### ISSUE THREAD

**Issue by dcangulo** [margelo/react-native-vision-camera#15]
I am encountering the following error when running the example app on Android.

```
BUILD SUCCESSFUL in 25s
187 actionable tasks: 2 executed, 185 up-to-date
info Connecting to the development server...
info Starting the app on "03157df32b9ac92d"...
Starting: Intent { cmp=com.mrousavy.camera.example/.MainActivity }
Error type 3
Error: Activity class {com.mrousavy.camera.example/com.mrousavy.camera.example.MainActivity} does not exist.
✨  Done in 31.25s.
```

What worked for me is this answer: https://stackoverflow.com/a/25633115/9375533

I made the following changes in https://github.com/cuvent/react-native-vision-camera/blob/main/example/android/app/build.gradle#L135
```diff
- applicationId "com.mrousavy.camera"
+ applicationId "com.mrousavy.camera.example"
```

Perhaps, we should update it? Or am I using it incorrectly?

**Comment by mrousavy** [comment]
Oh, looks like I missed that when I changed the names. Could you create a small PR for this?
