### ISSUE TITLE
🐛 Camera and Microphone permission errors are confused on Android

### ISSUE THREAD

**Issue by G0retZ** [margelo/react-native-vision-camera#162]
## What

The library reports wrong permissions error.
I've found the place that needs a change so I guess it's a simple typo
Just swap these 2 lines

https://github.com/cuvent/react-native-vision-camera/blob/b6a67d5cedb762f69a29c02b6f4184892f4d606f/android/src/main/java/com/mrousavy/camera/CameraView.kt#L221
https://github.com/cuvent/react-native-vision-camera/blob/b6a67d5cedb762f69a29c02b6f4184892f4d606f/android/src/main/java/com/mrousavy/camera/CameraView.kt#L224

Should I create a PR or you will do this by yourself?

### Logs

Not needed

## Reproducable sample

Just give only camera permission and see the error - it will say that camera permission is denied.
Or just give only mic permission and see the error - it will say that mic permission is denied.

## Environment

any

**Comment by G0retZ** [comment]
Here is the patch if someone needs it:

`diff --git a/node_modules/react-native-vision-camera/android/build/.transforms/511557eeebd9ea819a6492c074d783a3.bin b/node_modules/react-native-vision-camera/android/build/.transforms/511557eeebd9ea819a6492c074d783a3.bin
index 4c26b34..ea56f24 100644
--- a/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraView.kt
+++ b/node_modules/react-native-vision-camera/android/src/main/java/com/mrousavy/camera/CameraView.kt
@@ -218,10 +218,10 @@ class CameraView(context: Context) : FrameLayout(context), LifecycleOwner {
       val startTime = System.currentTimeMillis()
       Log.i(TAG, "Configuring session...")
       if (ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
-        throw MicrophonePermissionError()
+        throw CameraPermissionError()
       }
       if (ContextCompat.checkSelfPermission(context, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
-        throw CameraPermissionError()
+        throw MicrophonePermissionError()
       }
       if (cameraId == null) {
         throw NoCameraDeviceError()
`

**Comment by mrousavy** [comment]
Oh, nice catch! Would you mind creating a PR? I'm on mobile
