### ISSUE TITLE
❓Android Frame processor 

### ISSUE THREAD

**Issue by G0retZ** [margelo/react-native-vision-camera#164]
## Question

Do you have any estimation on Frame processor for Android?
Or mb you need some help with it?
Desperately need that :-)

**Comment by mrousavy** [comment]
I don't have an estimation, as it's really hard to plan this. After all, it's new "technology" that no one has used like this before.

I will start with the development next week, and I think most of the work is just getting the correct CMake setup. If you have experience with CMake, C++ or JNI, let me know.

**Comment by G0retZ** [comment]
Unfortunately I'm not that experienced in CMake, C++ or JNI
But once upon a time I was building and integrating pjsip (C++ and swig) with OPUS codec(before official support) and with the Android project.
From what I remember, the JNI Android API is much more reduced in comparison to the Java/Kotlin Android API.
And the key thing about image processing was that frames were gathered from Java code (Android API) and then passed to the C++ code (pjsip) that reused it's common code base for encoding and SIP routines...
And pjsip also passed the frames back to Java code for preview Views.
And also JNI works in the same Java threads (can create and use them).
So from that time I learned that JNI might be good for heavy calculations but not for heavy platform API usage :-)

Hope this info helps somehow.
