### ISSUE TITLE
❓ Is it possible to use it with react-native-webrtc? 

### ISSUE THREAD

**Issue by jsellam** [margelo/react-native-vision-camera#17]
Hi,
Thank you for this library, it's a very good job ! 

I'm working on video chat app with webrtc with react-native-webrtc.
In your documentation you say that we can use Frame Processor to build realtime video chat app. Have you more informations about it ?

react-native-webrc use it own "getUserMedia" implementation. Do you think it's possible to use your library too with webrtc ? and how ?

thx
Jeremie.

**Comment by mrousavy** [comment]
Hi!

Yes, it _will_ be possible to use VisionCamera for video chat applications. However I am still working on that part ("Frame Processors", see PR: https://github.com/cuvent/react-native-vision-camera/pull/2), so it is not ready yet.

Once frame processors are ready, they are like a sandbox. You can use plugins for your specific task (send frame over the network). So this means, once frame processors are released you will have to use a WebRTC plugin specifically designed for VisionCamera. Either you write that yourself, or react-native-webrtc does that.

The plugin will have to be written with JSI (C++), but I have a lot of examples on how to do that, and honestly it's not that difficult. I will share more details and examples once Frame Processors are available.

**Comment by mrousavy** [comment]
I just released [**2.0.0**](https://github.com/cuvent/react-native-vision-camera/releases/tag/v2.0.0), which finally includes Frame Processors.

This means you can create a WebRTC Frame Processor Plugin (see ["Creating a Frame Processor Plugin"](https://cuvent.github.io/react-native-vision-camera/docs/guides/frame-processors-plugins-overview/)) and start using WebRTC today. 🎉

> Note: Frame Processors are iOS only for now, I will do Android in a separate PR really soon. 💪
