### ISSUE TITLE
🐛 EXIF orientation

### ISSUE THREAD

**Issue by axeldelafosse** [margelo/react-native-vision-camera#287]
### What were you trying to do?

I wanted to upload a picture to S3 as a blob.

### What happened instead?

The blob doesn't keep the EXIF orientation so the rotation isn't correct. 

For example:
```
const blob = await (await fetch(photo.uri)).blob();
await fetch(url, {
  method: 'PUT',
  body: blob
});
```

Note that this is working correctly when getting a picture from `expo-image-picker` for example.

### Device

iPhone 11 Pro, OnePlus 9

### VisionCamera Version

2.4.1

### Additional information

- [X] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/react-native-vision-camera/issues) and found none.

**Comment by mrousavy** [comment]
Hey Axel 👋
So this happens both on iOS and Android?

**Comment by axeldelafosse** [comment]
Hey Marc! Yes!

**Comment by mrousavy** [comment]
Hey - I'm tracking Orientation in this feature request/issue now: https://github.com/mrousavy/react-native-vision-camera/issues/1891 ✨ 

Make sure to upvote or sponsor to support this feature, and leave a comment if you have any additional thoughts/ideas.
