### ISSUE TITLE
✨ How do I enable/disable the shutter sound

### ISSUE THREAD

**Issue by jzxchiang1** [margelo/react-native-vision-camera#311]
### Question

How do I enable or disable the shutter sound when taking a photo?

For some reason, when testing on my physical iPhone device, the sound plays when flash is off but doesn't play when flash is on.

Is this customizable? Thanks!

### VisionCamera Version

2.4.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
The shutter sound is always played in the image capture pipeline:


![](https://i.stack.imgur.com/ZkT8g.png)


But it looks like this actually can be customized by disposing the sound (see [this SO post](https://stackoverflow.com/a/55235949/5281431)). I'll mark this as a feature request and get to this soon

**Comment by mrousavy** [comment]
yeah it's pretty easily possible - will take a look soon. Does the shutter sound also play on Android?

**Comment by PABourdais** [comment]
On android native camera there is a shutter sound

**Comment by siddharthkr** [comment]
any update on this guys ?

**Comment by JurianBoots** [comment]
Hey @mrousavy, any update? This feature would be awesome! :)

**Comment by mrousavy** [comment]
Hey @JurianBoots, unfortunately not yet. I've had higher priorities in the past few days, such as my [agency Margelo](https://margelo.io), as well as other issues/PRs in VisionCamera/MMKV created by [my GitHub sponsors](https://github.com/sponsors/mrousavy).

**Comment by wassgha** [comment]
Could we please prioritize either this, or taking snapshots on iOS? I'm trying to make blurry previews of the camera, ideally this would be a low-quality snapshot but since that's not available on iOS I resorted to taking photos which plays the shutter sound even though the user did not trigger the photo.

**Comment by mrousavy** [comment]
> Could we please prioritize either this

Sure, you can prioritize this. Shoot me a PR if you have a working change.

**Comment by wassgha** [comment]
Yea just a sec

**Comment by wilav-dev** [comment]
Hello, any update?

**Comment by zymronak** [comment]
I found a way to disable the shutter should

1. open PhotoCaptureDelegate
2. find func photoOutput
3. add given line into the function and rebuild the app ```
// dispose system shutter sound
    AudioServicesDisposeSystemSoundID(1108)
```

**Comment by RONAKDHOLARIYA** [comment]
I found a way to disable the shutter should 
1. open PhotoCaptureDelegate
2. find func photoOutput
3. add given line into the function and rebuild the app 
```
// dispose system shutter sound 
AudioServicesDisposeSystemSoundID(1108) 
```

**Comment by mrousavy** [comment]
Hey! I just implemented this in V3! :) https://github.com/mrousavy/react-native-vision-camera/pull/1702

**Comment by jagdeepChicmic** [comment]
file shoes merged but code not reflected in 2.16.1 version(for ios)

**Comment by jeemercado** [comment]
@mrousavy any way we could update this for V2?

**Comment by mrousavy** [comment]
Hey - no, this is a V3 feature. I'm not adding any more features to V2, as I already spend a lot of time on V3 and I don't have any more free time to dedicate to V2.
