### ISSUE TITLE
Camera Launches but has no UI available to take a picture (Android)❓ 

### ISSUE THREAD

**Issue by Alih789** [margelo/react-native-vision-camera#320]
### Question

Is there something I need to pass to make the UI show up on the camera view? -- there is currently no button for me to press when in the camera view, just shows the thing I am trying to take a picture of. I am using an emulator if that makes a difference.

### What I tried

Following the docs, I created a reference item :  const camera = useRef() -- it would crash otherwise.
I also set the 'photo' prop to 'true' in my component but still nothing. I tried to add a custom image to overlay the camera view but that crashed everything. I feel like I'm misunderstanding something fundamental. Thanks in advance...

### VisionCamera Version

2.4.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Hi! The Camera library itself does not come with an overlay or a "button to press". You have to create that yourself using React code.
