### ISSUE TITLE
🐛 Cannot install with RN 0.65.1

### ISSUE THREAD

**Issue by jp928** [margelo/react-native-vision-camera#390]
### Question

Cannot install with react-native 0.65.1

### What I tried

yarn add react-native-vision-camera
pod install 

run react-native run-ios
I got
ios/Pods/Headers/Public/RCT-Folly/folly/portability/Config.h:20:10: 'folly/folly-config.h' file not found

### VisionCamera Version

2.6.1

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Which Reanimated version are you using?

**Comment by mrousavy** [comment]
Why is this a question and not a bug report?

**Comment by jp928** [comment]
@mrousavy  
I am sorry I felt it was my problem not a bug.
latest.2.2.0

**Comment by mrousavy** [comment]
Try with their latest alpha (2.3.something)

**Comment by jp928** [comment]
I copied everything related to Rct-Folly from reanimated podspec. So far so good.

**Comment by TomWq** [comment]
How can I solve the same problem   

/Users/wangqiang/ttvc/TTvc/ios/Pods/Headers/Public/RCT-Folly/folly/portability/Config.h:20:10: 'folly/folly-config.h' file not found

**Comment by anhquan291** [comment]
> I copied everything related to Rct-Folly from reanimated podspec. So far so good.

Hi,
I'm facing the same problem after upgrade to RN 0.65.1 (Reanimated 2.3 alpha) . 
Could you show your pod file, please? BTW, I'm also facing another problem with Android. 
` A failure occurred while executing com.android.build.gradle.internal.res.ResourceCompilerRunnable`
My build.gradle file: 
`buildscript {
    ext {
        RNNKotlinVersion = "1.3.61"
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "20.1.5948944"
        firebaseMessagingVersion = "21.1.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21"
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath "com.google.gms:google-services:4.3.4"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}`
Any helps, please. Thank you guys so much.

**Comment by mrousavy** [comment]
The example app uses react-native 0.65.1 and builds fine, so unfortunately I cannot reproduce the error..  :(

https://github.com/mrousavy/react-native-vision-camera/blob/57efc0e315d45d895d73802557a47ccb9253dc94/example/ios/Podfile.lock#L31-L43

**Comment by anhquan291** [comment]
> The example app uses react-native 0.65.1 and builds fine, so unfortunately I cannot reproduce the error.. :(
> 
> https://github.com/mrousavy/react-native-vision-camera/blob/57efc0e315d45d895d73802557a47ccb9253dc94/example/ios/Podfile.lock#L31-L43

Hi, thanks for this amazing library. 
You know I got it worked on iOS with RN 0.64 but Android. So I decided to upgrade to 0.65.1 and use exactly the same packages version in the example app. Unfortunately, it doesn't work. Still trying to figure it out. Will keep it posted. 

Have a nice day. Thank you

**Comment by rodgomesc** [comment]
> > The example app uses react-native 0.65.1 and builds fine, so unfortunately I cannot reproduce the error.. :(
> > https://github.com/mrousavy/react-native-vision-camera/blob/57efc0e315d45d895d73802557a47ccb9253dc94/example/ios/Podfile.lock#L31-L43
> 
> Hi, thanks for this amazing library.
> You know I got it worked on iOS with RN 0.64 but Android. So I decided to upgrade to 0.65.1 and use exactly the same packages version in the example app. Unfortunately, it doesn't work. Still trying to figure it out. Will keep it posted.
> 
> Have a nice day. Thank you

@anhquan291  fell free to share any xcode build errors

**Comment by rodgomesc** [comment]
@anhquan291 fell free to share any xcode build errors

**Comment by anhquan291** [comment]
> @anhquan291 fell free to share any xcode build errors

Hi, I'm still facing this issue. Any suggestions? Thank you
<img width="769" alt="Screen Shot 2021-09-02 at 22 47 12" src="https://user-images.githubusercontent.com/17813202/131875681-aa7dd4b1-c020-4f04-9931-33e07279d89a.png">

**Comment by max-frai** [comment]
Same for me:

```
› Compiling react-native-vision-camera Pods/VisionCamera » JSIUtils.mm


❌  (ios/Pods/Headers/Public/ReactCommon/ReactCommon/TurboModuleUtils.h:13:10)

  11 | #include <string>
  12 | 
> 13 | #include <folly/Optional.h>
     |          ^ 'folly/Optional.h' file not found
  14 | #include <jsi/jsi.h>
  15 | 
  16 | #include <ReactCommon/CallInvoker.h>
```

**Comment by anhquan291** [comment]
> I copied everything related to Rct-Folly from reanimated podspec. So far so good.

Hi @jp928 . Any solutions yet? Thank you

**Comment by Kypsis** [comment]
Same exact issue with RN 0.65.1, Reanimated 2.3.0-alpha.2 and latest master of vision camera.

**Comment by jp928** [comment]
@anhquan291
I can share my solution here.

- You need Reanimated 2.3.0-alpha.2, not for this issue. But without this when you release, metro would not bundle your js file
- Path podspec for react-native-vision-camera using patch-package
```
diff --git a/node_modules/react-native-vision-camera/VisionCamera.podspec b/node_modules/react-native-vision-camera/VisionCamera.podspec
index 8cfe1c6..28ef782 100644
--- a/node_modules/react-native-vision-camera/VisionCamera.podspec
+++ b/node_modules/react-native-vision-camera/VisionCamera.podspec
@@ -2,6 +2,15 @@ require "json"
 
 package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 
+reactVersion = JSON.parse(File.read(File.join(__dir__, "..", "react-native", "package.json")))["version"]
+rnVersion = reactVersion.split('.')[1]
+folly_prefix = "RCT-"
+
+folly_flags = '-DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1 -DRNVERSION=' + rnVersion
+folly_compiler_flags = folly_flags + ' ' + '-Wno-comma -Wno-shorten-64-to-32'
+folly_version = '2020.01.13.00'
+boost_compiler_flags = '-Wno-documentation'
+
 Pod::Spec.new do |s|
   s.name         = "VisionCamera"
   s.version      = package["version"]
@@ -16,8 +25,14 @@ Pod::Spec.new do |s|
   s.pod_target_xcconfig = {
     "DEFINES_MODULE" => "YES",
     "USE_HEADERMAP" => "YES",
-    "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/ReactCommon\" \"$(PODS_TARGET_SRCROOT)\" \"$(PODS_ROOT)/Headers/Private/React-Core\" \"$(PODS_ROOT)/Headers/Public/React-hermes\" \"$(PODS_ROOT)/Headers/Public/hermes-engine\""
+    "HEADER_SEARCH_PATHS" => "\"$(PODS_TARGET_SRCROOT)/ReactCommon\" \"$(PODS_TARGET_SRCROOT)\" \"$(PODS_ROOT)/RCT-Folly\" \"$(PODS_ROOT)/Headers/Private/React-Core\" \"$(PODS_ROOT)/Headers/Public/React-hermes\" \"$(PODS_ROOT)/Headers/Public/hermes-engine\""
   }
+
+  s.compiler_flags = folly_compiler_flags + ' ' + boost_compiler_flags
+  s.xcconfig               = {
+    "CLANG_CXX_LANGUAGE_STANDARD" => "c++14",
+    "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost-for-react-native\" \"$(PODS_ROOT)/glog\" \"$(PODS_ROOT)/#{folly_prefix}Folly\" \"${PODS_ROOT}/Headers/Public/React-hermes\" \"${PODS_ROOT}/Headers/Public/hermes-engine\"",
+                               "OTHER_CFLAGS" => "$(inherited)" + " " + folly_flags  }
   s.requires_arc = true
 
   # All source files that should be publicly visible
```

- Run 
`rm -rf Pods && pod install` in your ios folder

**Comment by anhquan291** [comment]
@jp928  OMG, it works like charm. Thank you so much. Really appreciated. 

@Kypsis , @max-frai , @wq13718048209 . Modify Podspec of react-native-vision-camera as @jp928 fixed the issue on iOS.

**Comment by TomWq** [comment]
@jp928  thank you  , This is a very useful scheme.   @mrousavy  When will it be updated?  It's true that a lot of people have this problem.

**Comment by juliendevleeschauwer** [comment]
work for me with react-native-reanimated@2.3.0-alpha.3

**Comment by rodgomesc** [comment]
worked for me with `react-native-reanimated@2.3.0-alpha.3`, but i had to downgrade `react-native-screens` from `3.6.0` to `3.5.0` because ios build issues.

i saw this attempt to solve something [in a commit](https://github.com/software-mansion/react-native-reanimated/commit/2e8923e756fa867c12a9163ad14f914fe4a5836a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) to reanimated 2.3.0-alpha.3, but it looks like another problem appears in its place ˆ.ˆ

![image](https://user-images.githubusercontent.com/4893591/132534572-49f84ede-d5c5-4733-bcde-63d4b7b2e8c6.png)

**Comment by rodgomesc** [comment]
I've just updated the example of a plugin I've been developing using the latest version of react native and vision camera, maybe it will help if someone still has difficulties doing the update

https://github.com/rodgomesc/vision-camera-qrcode-scanner/commit/bc980885bb43313a08ea1d954d901a2ac4221d3c

**Comment by batical** [comment]
still does not work for me with react-native-reanimated@2.3.0-alpha.3

**Comment by jzxchiang1** [comment]
FWIW I don't have this error running VisionCamera 2.5.0 on RN 0.65.1 with reanimated 2.2.2 on iOS 14.

**Comment by mushan0x0** [comment]
Install the react-native-reanimated package to solve it.

**Comment by faustaleonardo** [comment]
```
"react": "17.0.2",
"react-native": "0.65.1",
"react-native-vision-camera": "2.4.1",
"react-native-reanimated": "^2.2.0",
```
I got it working by using those versions!
