### ISSUE TITLE
❓Is this library support square video?

### ISSUE THREAD

**Issue by AlkanV** [margelo/react-native-vision-camera#392]
### Question

Hello,

is it possible to record square videos with this package?

thanks

### VisionCamera Version

Latest

### Additional information

- [ ] I am using Expo
- [X] I have read the [Troubleshooting Guide](https://mrousavy.github.io/react-native-vision-camera/docs/guides/troubleshooting)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for similar questions [in the issues page](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22❓+question%22) as well as [in the discussions page](https://github.com/mrousavy/react-native-vision-camera/discussions) and found none.

**Comment by mrousavy** [comment]
Yes it is. Try choosing a `format` that has square video dimensions (see ["Camera Formats"](https://mrousavy.github.io/react-native-vision-camera/docs/guides/formats)).

If none is available, then it isn't supported by your Phone and you will have to manually crop the video somehow (post-processing)

**Comment by AlkanV** [comment]
Hello, @mrousavy,

Thank you so much for the answer. 

Best wishes,

**Comment by nica0012** [comment]
Hi @AlkanV What did you end up using to get square video?

**Comment by powerpivar** [comment]
Hi @AlkanV, same question, how did you achieve the square video?

**Comment by AlkanV** [comment]
@nica0012 @powerpivar i did not use this library yet so i have no answer for it.
