### ISSUE TITLE
✨  Mention Frame Processor getting started steps more explicitly

### ISSUE THREAD

**Issue by ldstein** [margelo/react-native-vision-camera#420]
### What feature or enhancement are you suggesting?

Hi,

This is a superb library. FrameProcessors are a game changer. I have a couple of suggestions for the getting started guide to help new users such as myself :)

1. You have to follow the installation steps as descibed at https://www.reanimated2.com/docs/installation
2. You must add `import Reanimated from 'react-native-reanimated'` to avoid `undefined is not a function` render errors with worklets.

The second point in particular was a gotcha for me and didn't seem particularly well explained.

**Edit** - Apologies, this maybe a configuration issue on my end. The example at https://github.com/rodgomesc/vision-camera-qrcode-scanner works without the above steps. Not sure why my blank `npx react-native init AwesomeProject` required the the above steps to suppress the `undefined is not a function` error. Investigating further.

### What Platforms whould this feature/enhancement affect?

iOS, Android

### Alternatives/Workarounds

Trawl the Github / Stackoverflow / Google for working solutions.

### Additional information

- [X] I agree to follow this project's [Code of Conduct](https://github.com/mrousavy/react-native-vision-camera/blob/main/CODE_OF_CONDUCT.md)
- [X] I searched for [similar feature requests in this repository](https://github.com/mrousavy/react-native-vision-camera/issues?q=is%3Aopen+is%3Aissue+label%3A%22✨+enhancement%22) and found none.

**Comment by du5rte** [comment]
@ldstein you're a lifesaver!! I was stuck on that error until I saw this! 🎉
