### ISSUE TITLE
✨ RAW Photo Capture

### ISSUE THREAD

**Issue by mrousavy** [margelo/react-native-vision-camera#73]
Currently you can only take .jpg photos. There are use-cases where you'd also want to take photos in the camera's RAW format for additional post-processing.

This should be configurable by setting a `raw: true` parameter in the `takePhoto(...)` func

* [`AVCapturePhotoSettings::init(rawPixelFormatType:)`](https://developer.apple.com/documentation/avfoundation/avcapturephotosettings/1648662-init)

This would use Apple ProRAW on iOS, and RAW YUV on Android.

WWDC resource: https://developer.apple.com/videos/play/wwdc2021/10160/

**Comment by aliraza-noon** [comment]
@mrousavy I think this would be a good addition, I have a use case for this in my app I am currently looking for library that does support this I can't implement the bridge myself I have very limited knowledge of CameraX

There is an issue open for `react-native-camera` https://github.com/react-native-camera/react-native-camera/issues/2951

**Comment by akashraj9828** [comment]
Any update on this? ...This is a useful feature for many people I'm sure

**Comment by MaykolSantos** [comment]
Are there any news about this feature?
I'm currently working on an app that requires RAW photos, but AFAIK VisionCamera does not support raw yet

**Comment by ontheway16** [comment]
no raw support yet? Thats a big miss.

**Comment by mrousavy** [comment]
New issue to track this: #1851
