### ISSUE TITLE
✨ Android: Correctly implement Format (Resolution, FPS)

### ISSUE THREAD

**Issue by mrousavy** [margelo/react-native-vision-camera#76]
### Getting Formats with FPS higher than 30 doesn't seem to work.

I feel like something in the `getAvailableCameraDevices` code is wrong:

https://github.com/cuvent/react-native-vision-camera/blob/dff8fc71788311c324e6eb80976a6ec50596d3e5/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L205-L220

Maybe I shouldn't use `MediaRecorder::class.java` here?:

https://github.com/cuvent/react-native-vision-camera/blob/dff8fc71788311c324e6eb80976a6ec50596d3e5/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L201

I think the FPS-setting logic here works, as it also works for e.g. 15 FPS:

https://github.com/cuvent/react-native-vision-camera/blob/d85126d883feffcd6189135042420a8d89b153cf/android/src/main/java/com/mrousavy/camera/CameraView.kt#L280-L292

But CameraX doesn't support "high-speed video capture" yet, so anything high-speed (such as slow-mo, 120FPS, 240FPS) is not yet supported.

### Resolution doesn't seem to correctly apply to Preview

I think I had some issues with setting the Resolution from a Format where I wasn't sure which resolution to use for the preview - I'll have to test that though. I think the ImageReader and VideoRecorder had correct resolutions.

### Resolution is always the same for Photo and Video

I don't think that the VideoRecorder resolution is always the same as the ImageReader resolution, those actually have to be different.

https://github.com/cuvent/react-native-vision-camera/blob/dff8fc71788311c324e6eb80976a6ec50596d3e5/android/src/main/java/com/mrousavy/camera/CameraViewModule.kt#L236-L239

**Comment by McFly78** [comment]
Hello,

For your issue "Resolution doesn't seem to correctly apply to Preview"
I confirm you that the Preview Resolution is not good on Android.
The image displayed on the screen is zoomed.

On IOS everything is fine !

**Comment by Alex1899** [comment]
having this issue

**Comment by nica0012** [comment]
@Alex1899 the zooming is happening for me too on IOS, only for 30FPS (photos and videos). 60FPS the image/video output is exactly as expected (1:1 / 4:3). Been trying to find a solution for 2 days...

**Comment by mrousavy** [comment]
Hey! I've rewritten the entire Android codebase of VisionCamera from CameraX to Camera2 in the efforts of [✨ VisionCamera V3](https://github.com/mrousavy/react-native-vision-camera/issues/1376).

I just now completed the Camera2 rewrite and I believe the core structure is running, but there might be some edge cases to iron out.

Multi-cameras should now work! 🎉 

Here's an instruction on how we can test that: https://github.com/mrousavy/react-native-vision-camera/pull/1674#issuecomment-1684104217

**Comment by mrousavy** [comment]
some Samsungs say they have 60 FPS but when you try to use 60 FPS it just shows a blackscreen. again, samsung making it really painful.
