### ISSUE TITLE
✨ Android: Return Video size and duration

### ISSUE THREAD

**Issue by mrousavy** [margelo/react-native-vision-camera#77]
On Android the [video duration](https://cuvent.github.io/react-native-vision-camera/docs/api/interfaces/videofile.videofile-1#duration) and [size](https://cuvent.github.io/react-native-vision-camera/docs/api/interfaces/videofile.videofile-1#size) are not set correctly because CameraX doesn't provide that information in the Callback.

https://github.com/cuvent/react-native-vision-camera/blob/dff8fc71788311c324e6eb80976a6ec50596d3e5/android/src/main/java/com/mrousavy/camera/CameraView%2BRecordVideo.kt#L32-L36

The only workaround for this would be reading the Video's Metadata, but that's an extra overhead I don't want to introduce.

With frame processors I'm going to have to create a custom Video recorder and encoder anyways, I can manually use a stopwatch for this then. So #2 _probably_ fixes this issue.

**Comment by hirbod** [comment]
@mrousavy would love to have feature parity here. Missing the duration for android.

**Comment by mrousavy** [comment]
This is actually implemented on Android already with one of my latest PRs.

**Comment by hirbod** [comment]
Oh really? Duration is there for android? I just implemented ffprobe and some crazy async tasks for it :D

**Comment by mrousavy** [comment]
Did you check if it was there?

**Comment by hirbod** [comment]
Nope, I saw this ticket and I knew it wasn't there couple of weeks ago.

**Comment by hirbod** [comment]
Yes, it is there... `yarn remove react-native-ffmpeg-kit`
:D
