### ISSUE TITLE
How can i install type definitions? ❓ 

### ISSUE THREAD

**Issue by me1k** [margelo/react-native-vision-camera#8]
## How to use the module without type definitions?

Hi, i saw your post about the Camera library on Reddit and directly wanted to try it out in my Typescript project. I also can see that you use Typescript in the Project. But my project is complaining, that there are no type definitions. How can i install them or use your module now? :)

**Comment by mrousavy** [comment]
Hey! Types are available in the latest version, that's `1.0.0-alpha.6`. Which version are you on?

**Comment by me1k** [comment]
Thank you for your answer! When i install it with yarn, i installs 1.0.0-alpha.1

**Comment by mrousavy** [comment]
Yes, that's because only alphas are available on npm. In the README I have mentioned that you have to install it with the @alpha suffix (Or manually change the version in package.json)

**Comment by me1k** [comment]
I changed it manually in the package.json and it works fine now. Thank you very much. I'm looking forward to use your camera component :)
